language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
  - "pyflakes characters private_messages quests rpg_auth world"
script: "python ./manage.py test --settings=soj.settings_travis"
