language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - "pyflakes characters private_messages quests rpg_auth world tasks"
script: "python ./manage.py test --settings=soj.settings_travis"
